class_name IdTypes
extends RefCounted

const ROLES := ["GUARDIAN", "VANGUARD", "ASSAULT", "ARTILLERY", "SPECIALIST", "MEDIC"]
const ATTACK_TYPES := ["PHYSICAL", "ENERGY", "ANOMALY"]
const DEFENSE_TYPES := ["ARMOR", "BARRIER", "WARD"]
const POSITIONS := ["FRONT", "FRONT", "MIDDLE", "MIDDLE", "BACK"]
const STATUS_EFFECTS := ["STUN", "SILENCE", "SLOW", "HASTE", "TAUNT", "DEF_DOWN", "ATK_DOWN", "DAMAGE_OVER_TIME", "HEAL_OVER_TIME", "SHIELD", "INVULNERABLE", "CLEANSE", "DISPEL"]

